run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - bodyclose
    - contextcheck
    - durationcheck
    - errname
    - errorlint
    - copyloopvar
    - goconst
    - gocritic
    - gofmt
    - goimports
    - gosec
    - misspell
    - nilerr
    - prealloc
    - revive
    - unconvert
    - unparam
    - whitespace

linters-settings:
  govet:
    shadow: true
  revive:
    rules:
      - name: exported
        arguments:
          - "disableStutteringCheck"
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - hugeParam

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - unparam
